name: py27
channels:
  - defaults
dependencies:
  - python=2.7.15
  - numpy=1.15.1
  - pandas=0.23.4
  - inspect
  - matplotlib
  - pip:
    - mlflow
    - scikit-learn=0.21.2
    - seaborn=0.9.0
