name: py36
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pandas=0.23.4
  - inspect
  - matplotlib
  - pip:
    - mlflow
    - scikit-learn=0.21.2
    - seaborn=0.9.0

